In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('FrozenLake-v0')

In [3]:
env.render()


SFFF
FHFH
FFFH
HFFG


In [4]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [6]:
print ("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.5645


In [7]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[1.88363011e-01 4.07568043e-03 4.11064606e-03 1.33829362e-02]
 [2.25245544e-04 8.47564644e-04 7.38516893e-04 1.71633279e-01]
 [7.26532688e-02 0.00000000e+00 4.96229198e-04 7.04610979e-04]
 [0.00000000e+00 2.05963336e-03 0.00000000e+00 0.00000000e+00]
 [1.53468375e-01 5.30925739e-03 3.37083528e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.45895205e-03 7.82175150e-06 2.91668091e-03 3.58331432e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.59728299e-03 1.40186452e-01]
 [0.00000000e+00 9.90093607e-02 0.00000000e+00 0.00000000e+00]
 [2.29259229e-02 1.45898494e-03 0.00000000e+00 1.12480419e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.48075253e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.09576924e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.